### ISSUE TITLE
导入账户：通过keystore文件导入账户时，选择的文件不是keystore应该提示错误，而不是提示输入密码

### ISSUE THREAD

**Issue by yeealbert** [nuls-io/nuls_2.0#288]
版本：NULS2.0Alpha1
严重程度：一般
优先级：3
操作步骤：
1、使用importkeystore命令导入账户地址，选择非keystore类型的文件执行
实际结果：
1、提示输入密码
预期结果：
提示文件错误

附件：![image](https://user-images.githubusercontent.com/44149471/54899555-18c04880-4f0b-11e9-8b66-1066f439472a.png)

**Comment by lijunzhou** [comment]
keystore只是一个普通的文本文件。
