### ISSUE TITLE
Command: withdraw<Address><TxHash> doesn't have any amount parameter?

### ISSUE THREAD

**Issue by dirmansebastian** [nuls-io/nuls_2.0#296]
i guess now it withdraw all staked amount, we need an amount parameter in case we want to withdraw just a part of the amount

**Comment by tag0313** [comment]
Now the withdrawal of entrusted transaction is aimed at a entrusted transaction, so the withdrawal of entrusted transaction by Switzerland can not be only a part of the amount of the withdrawal of entrusted transaction.

**Comment by yeealbert** [comment]
共识节点的退出委托是根据加入委托的hash判定的，目前只能进行某一笔委托进行退出，不能指定amount退出
