### ISSUE TITLE
shutdown.sh (sometimes) kills parallel running NULS 1.0 clients

### ISSUE THREAD

**Issue by mhex** [nuls-io/nuls_2.0#304]
shutdown.sh sometimes kills parallel running NULS 1.0 clients, both mainnet and testnet beta. Sometimes only the mainnet client is killed, sometimes the testnet beta client, sometimes both or none. It's not deterministic.

**Comment by yeealbert** [comment]
问题已修复

**Comment by lijunzhou** [comment]
Will be fixed in alpha3.
