### ISSUE TITLE
转账一定时间后，查询余额偶尔为0

### ISSUE THREAD

**Issue by qinyifeng1226** [nuls-io/nuls_2.0#305]
严重程度：严重
优先级：3
操作步骤：
1、新建一个地址作为节点地址
2、从创世块地址转账25000100000000给新创建的地址
3、等待30秒后，分别调用账本接口getBalance、getBalanceNonce查询余额
实际结果：
1、两个接口返回余额都为0；
预期结果：
1、余额为25000100000000；
![getBalanceIsZero](https://user-images.githubusercontent.com/43125370/56376209-d5bb7180-6239-11e9-94b9-35f70a097df3.png)
[getBalanceIsZero.txt](https://github.com/nuls-io/nuls_2.0/files/3095282/getBalanceIsZero.txt)
@lanjinsheng

**Comment by lanjinsheng** [comment]
需要确认是否正常出块中？以及交易是否正常被打包入块？
 单从业务逻辑看，目前该部分转账逻辑已经测试正常。
