### ISSUE TITLE
取消委托后再次委托失败，账本模块查询余额不足

### ISSUE THREAD

**Issue by qinyifeng1226** [nuls-io/nuls_2.0#306]
严重程度：严重
优先级：2
操作步骤：
1、新建一个地址作为节点地址
2、从创世块地址转账25000100000000给新创建的地址
3、节点委托20000000000000
4、委托成功后过一分钟，将委托取消
5、取消委托成功后，再次委托
实际结果：
1、委托失败
预期结果：
1、委托成功
分析：
根据日志及调试，发现共识模块再次发起委托交易时，交易模块返回失败，再往下，交易模块在调用账本模块的提交未确认交易时，账本模块验证时，余额不足，但是通过单独的单元测试返回余额为22999999600000，是大于委托最小金额的
[depositAgainError.txt](https://github.com/nuls-io/nuls_2.0/files/3095341/depositAgainError.txt)
[depositAgainError_leger.txt](https://github.com/nuls-io/nuls_2.0/files/3095342/depositAgainError_leger.txt)
[depositAgainError_tx.txt](https://github.com/nuls-io/nuls_2.0/files/3095343/depositAgainError_tx.txt)
@lanjinsheng

**Comment by lanjinsheng** [comment]
已经修复！
