### ISSUE TITLE
stopagent command is not working

### ISSUE THREAD

**Issue by mhex** [nuls-io/nuls_2.0#307]
The stopagent command seems not to work. The agent is still there. The agent is ned_1

`nuls>>> stopagent tNULSeBaMr4pNM47akScnFUJgQTmNBhYqw6shk
Enter your account password*********
"042c5d16e9c0bfa915305f5bf29da05b2e77142608e1a46e2266354a39766355"
nuls>>> stopagent tNULSeBaMr4pNM47akScnFUJgQTmNBhYqw6shk
Enter your account password*********
"723b6ae9598d2f7c91b7129616b8641e7871564c434384605bf94737adc475ef"
nuls>>> stopagent tNULSeBaMr4pNM47akScnFUJgQTmNBhYqw6shk
Enter your account password*********
"7feb7ef16f406d580f1e60fe348e767bbccd0ada1910f60b9da8958776bf7d50"
nuls>>>`

**Comment by yeealbert** [comment]
问题已修复
![image](https://user-images.githubusercontent.com/44149471/57343946-e6477380-7177-11e9-9cf1-0cb09f60f176.png)

**Comment by mhex** [comment]
I still cannot stop my agent
![stopagent](https://user-images.githubusercontent.com/843533/57349179-72966e00-7159-11e9-9455-08c558fe2871.png)

None of the returned transaction hashes exists

3cb9b77eb7008bb2b6eec9db1f3950a9282fb23971624d0e7d4ef4737de49b5c
7a3277e1505936e8c13f3aa432718b72ffa8cde78055b889c326826ee8e4bee0
b7a2c203a6a85ba93bb80122249bcd1f1d66ffb2f4735aae037d72d6300bd966
8dec0d7131b3a255f6fe2ec7f9d57455a17b47cd71bae1bf8b589b9557f27bea

**Comment by mhex** [comment]
The explorer still shows the agent http://alpha.nulscan.io/consensus/info?hash=bf507f7f3a73830289a75d66dd35d28730779cda80df2c8ec001713aa92c4788&tabName=first with the address tNULSeBaMr4pNM47akScnFUJgQTmNBhYqw6shk  With this address the stopagent command does not work as can be seen on the screenshot.
