### ISSUE TITLE
Withdrawn deposit is not immediately usable

### ISSUE THREAD

**Issue by mhex** [nuls-io/nuls_2.0#308]
After withdrawing a deposit it's not usable either for transfering or depositing for in my case 20 Minutes despite the balance shows up as usable. 

Here an example with an account with a usable balance of 52k.

`nuls>>> getaccount tNULSeBaMjiyLX3aPdq9oanVhfFb9hp114YEgX
{
  ...
  "alias" : null,
  "baglance" : {
    "available" : "51966.45677167",
    "total" : "251966.45677167",
    "freeze" : "200000"
  },
  "address" : "tNULSeBaMjiyLX3aPdq9oanVhfFb9hp114YEgX",
  "pubkeyHex" : "03f753ecc68ca404725fc83fec9a61ee69dbe21d22e1416b63608f7d0afec01e38"
}
`
However, it's not possible to deposit or transfer it

`nuls>>> deposit tNULSeBaMjiyLX3aPdq9oanVhfFb9hp114YEgX c10eab12bf43460a4541ddd199adf41fd05351bd38d2f00cb77d6fddf988cca9 51000
Please enter the password.
Enter your password:*********
Failed
`

`
nuls>>> transfer tNULSeBaMjiyLX3aPdq9oanVhfFb9hp114YEgX tNULSeBaMjWuGgCGG5v7XriHBPvw2gdCFUrsiV 51000
Enter your account password*********
Failed
nuls>>> transfer tNULSeBaMjiyLX3aPdq9oanVhfFb9hp114YEgX tNULSeBaMjWuGgCGG5v7XriHBPvw2gdCFUrsiV 1000
Enter your account password*********
Failed
nuls>>> 
`
I imported the account on another machine running Alpha 2.1. but the same errors. Blocks are synced.

**Comment by mhex** [comment]
For some reason 10 Minutes later transfer and deposit worked again.

**Comment by yeealbert** [comment]
问题已修复
![image](https://user-images.githubusercontent.com/44149471/57344301-47bc1200-7179-11e9-8693-404297b7f8c1.png)

**Comment by mhex** [comment]
This screenshot is not showing the issue. The the failed transaction happens after _withdrawing_ from an agent. In the screenshot i don't see a withdrawing.
